### ISSUE TITLE
Produce draft Loose Coupling guidance

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1437]
Produce a draft loose coupling architecture guidance document that includes:

- conceptual architecture
- Cloud impact (latency and egress costs)
- data management impacts
- pace layered architecture (UX and API/Data layer)
- BDM's target architecture vision

[link to deck](https://014gc.sharepoint.com/:p:/r/sites/TargetITSolutionDeliveryModel/Shared%20Documents/Loose_Coupling_Discussion_Facilitator.pptx?d=w59c456724c8d4e18a17d462da7fc7dc1&csf=1&web=1&e=bcf79u)

This as part of TSDM/Architecture direction on loose coupling, ABB strategy, and to facilitate discussions with CDO + DAS teams.

- [x] Present to DAS
- [x] Present to some Architects (e.g. EA, Sol Arch)
- [x] Present to BDM architects

**Comment by remyb2canada** [comment]
Getting two examples:
- [ ] NAR
- [ ] BSI's dev team (involved in web apps that seem to exchange info without being master data owners)

**Comment by remyb2canada** [comment]
Presented to IITB architects (EA, Sol Arch, Technical Arch), not BDM.
Got support, no road blockers but a few concerns:

- competing architecture principles (e.g. tell me once vs no-customization). Interpreting as tell me once means storing the information in one system, with the other ones having to fetch it on demand. Where would we sit this in a decision hierarchy?
- If we have cache (copies of data), how do we determine trustworthiness of the copy?

**Comment by remyb2canada** [comment]
meeting with BDM scheduled for Jan 26th
meeting with DAS scheduled for Feb 3rd

**Comment by remyb2canada** [comment]
Enough done. Closing issue as I update the TSDM to fit the Data component.
