### ISSUE TITLE
Finalize minimum code Acceptance Criteria for all Micro-Acquisitions

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1472]
- [ ] Complete research into best practices ....Is there generic criteria that can be used for all code that is delivered?  Automated tests?  Security?
- [ ] Work with Solutions Architecture to see what of their work we can link to
- [ ] Meet with IT Security

**Comment by RachelMuston** [comment]
Research gathered here: https://014gc.sharepoint.com/:w:/s/GCDevEx/EfmEEwRP1_dKuoHZ5eH4QuIB4IgMVlJ1cnWBMgIGvqAWIA?e=Oy2v25

**Comment by RachelMuston** [comment]
Evaluate GitHub's Code Scanning feature as part of the QA process to find any vulnerabilities. From the folks at CDS: "we had Semmle's previous offering LGTM as a requirement for all CDS OS projects, and so will transition it all over to this (code scanning). It really helps with catching errors."

https://github.blog/2020-09-30-code-scanning-is-now-available/

**Comment by RachelMuston** [comment]
Email sent to security requesting a meeting
