### ISSUE TITLE
Finish CSPS Finance courses

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1473]
- [x] [F111, Financial Management Control Frameworks](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/financial-management-control-frameworks-f111)
- [x] [F112, Government Planning, Budgeting, Reporting and Evaluation Cycle](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/government-planning-budgeting-reporting-and-evaluation-cycle-f112)
- [x] [F113, Financial Management Systems](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/financial-management-systems-f113)
- [x] [F303, The System of Government from a Financial Perspective](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/system-government-financial-perspective-f303)
- [ ] [F304, Applying key concepts financial management](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/applying-key-concepts-financial-management-f304), 7.5h in virtual classroom, material available for download
- [x] [G380, Responsible use of public funds](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/responsible-use-public-funds-g380)

maybe
- [ ] [C220, Preparing a business case](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/preparing-business-case-c220) (no longer available, even the course materials)
- [x] [T038, Developing an Effective Business Case](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/developing-effective-business-case-t038)
- [ ] [T945, PRINCE 2 Project Planning and Risk Management](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/prince-2-project-planning-and-risk-management-t945)
- [x] [C210, Introduction to Risk Management](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/introduction-risk-management-c210), prerequisite for C361
- [ ] [F150, Risk Management for Finance Professionals](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/risk-management-finance-professionals-f150), 7.5h in classroom, material available for download
- [ ] [C361, Integrated Risk Management](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/integrated-risk-management-c361), 3rd in a series: C210, F150, C361
- [ ] [T404, risk management basics](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/risk-management-basics-t404), not available, instead recommended to:
  - [x] [I633, Agile project scheduling and monitoring](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/agile-project-scheduling-and-monitoring-i633)
  - [x] [T919, Project initiation and planning](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/project-initiation-and-planning-pmbokr-guide-sixth-edition-t919)
  - [x] [D013, Responding effectively to risks](https://learn-apprendre.csps-efpc.gc.ca/application/en/content/responding-effectively-risks-d013)
