### ISSUE TITLE
Get up to speed on CFOB's directives and standards

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1475]
- [x] CFOB's Policy on PM and Programme Management
- [x] CFOB's Directives (Benefits Management, PMCD, Programme Mgt, PM)
- [x] CFOB's Standards (Programme Mgt, PM, PMCD)
- [x] CFOB's Procedures (dashboard reporting template)
- [x] CFOB's PMIS Monthly Analysis Criteria
- [x] CFOB's Guide to Business Case
- [x] CFOB Guide to Risk Management
- [x] CFOB Guide to Stage Exception Management
- [x] CFOB Guide to the Investment Proposal Intake Form
- [x] CFOB IPPM's Saba course [PjM-100: An Introduction to the Management of Investment Projects at ESDC: Project and Programme Management Practice](https://esdc.sabacloud.com/Saba/Web_spf/CA1PRD0006/app/me/learningeventdetail/cours000000000072665?regId=regdw00000000162065)
- [ ] Review with BPMO other reporting criteria

As, although CFOB does not prescribe project management to manage investments, their standards and procedures seem to be heavily geared towards PM-types of management.

**Comment by remyb2canada** [comment]
good enough
With BPMO, will work on it in a different issue (most likely as part of the evaluation for producing a framework)
