### ISSUE TITLE
Triage process for micro-acquisition requests

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1512]
- [ ] decide on buckets/types of requests (what makes a request simple vs complex - 'pure code' vs. say a video where the raw files could be open source/creative commons licenced, tech capabilities of the requesting team etc.)
- [ ] determine time that IT Strategy would have to spend on those requests (meeting with clients, helping with opportunity text, helping evaluate suppliers, helping to assess code)
- [ ] based on above do a rough calculation of how many requests we 'could' handle - e.g. how many if all the requests are simple, how may if all the requests are complex
- [ ] prepare a triage process for incoming requests - at what point do we turn requests away due to IT Strategy capacity?
- [ ] what is our target ratio (in an ideal world), how many simple vs. complex requests?

**Comment by RachelMuston** [comment]
This is on hold as it is not required for the launch in June

**Comment by RachelMuston** [comment]
This is on hold as we do not have a large quantity of requests coming in that would require a triage process
