### ISSUE TITLE
Present findings to stakeholders

### ISSUE THREAD

**Issue by gcharest** [sara-sabr/ITStrategy#1556]
Close the study by presenting findings to stakeholders for implementation.

**Comment by gcharest** [comment]
- [ ] IT Strategy Director
- [ ] IT Strategy Ex Director
- [ ] SABR DG
- [ ] Governance Manager
- [ ] Chief of Staff
