### ISSUE TITLE
Project to Product related materials

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1582]
- [x] [How to guarantee Failure in your Agile DevOps Transformation](https://www.cmcrossroads.com/article/how-guarantee-failure-your-agile-devops-transformation?page=0%2C0)
- [x] [A truly Agile Federal Government focuses on flow](https://www.tasktop.com/blog/a-truly-agile-federal-government-focuses-on-flow/)
- [x] [The Cost Center Trap](http://www.leanessays.com/2017/11/the-cost-center-trap.html)
- [x] [A leader's framework for decision making](https://hbr.org/2007/11/a-leaders-framework-for-decision-making)
- [x] [DORA Visibility of work](https://cloud.google.com/solutions/devops/devops-process-work-visibility-in-value-stream)
