### ISSUE TITLE
Get buy-in from IITB stakeholders (business case)

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1660]
Internal to IITB, in order:
- [x] BRM (MC and MB), June 4th
- [ ] IM (with insights from AS), June 21th
- [x] IITB Resource Management, June 3rd
- [x] IITB Gov OCIO (because of governance), June 10th
- [x] IITB HR, June 8th -> need to involve HRSB
- [x] Enterprise Architecture, Tech Arch June 9th
- [x] Solution Architecture, June 10th
- [x] IT Security, July 7th
- [x] Release Management (and ITSM), June 29th

Stakeholders consulted (and with buy-in) will be listed in the [exec-level Business Case summary slide](https://014gc.sharepoint.com/:p:/r/sites/TargetITSolutionDeliveryModel/Shared%20Documents/business-case-product-mgt-fw/ProductManagement-Exec-BusinessCase.pptx?d=w6f1c28c8c3d04e1d8b58def3ca066cce&csf=1&web=1&e=LXKNhu)

[2 pager debrief for executives](https://014gc.sharepoint.com/:w:/r/sites/TargetITSolutionDeliveryModel/Shared%20Documents/business-case-product-mgt-fw/SeniorLeader-Briefing.docx?d=w6479dcc767bd4abc9c80031627b1abf2&csf=1&web=1&e=bzDQxn)
