### ISSUE TITLE
Value Management

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1705]
- [x] https://www.pmi.org/learning/library/strategic-value-management-business-benefits-8699
- [x] https://www.pmi.org/learning/library/earned-value-management-systems-analysis-8026
- [x] https://www.pmi.org/learning/library/value-earned-value-management-6232
- [x] https://www.insight.com/en_US/content-and-resources/tech-tutorials/using-earned-value-to-monitor-project-performance.html (calculating earned value)
