### ISSUE TITLE
Broadcast Product Management initiative

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1837]
Not about buy-in but to communicate what the team is working on and the angle it is taking.

- [x] Tech Debt / TDRO (though not formally part of the branch initiative stakeholder list) - issue #1906)
- [ ] Comms and Change Management
- [ ] BSI / SEPS (because of Job Bank)
- [ ] BSIM / Interop (because of YESS)
- [ ] BSI (DG level) _all ESDC ADMs are clients of BSI_
- [ ] Enteprise Digital Solutions (DG Level) _enterprise-level capabilities_
- [x] SABR Extended Management Committee
- [x] AppDev Senior Advisors
- [x] DevOps  CoE (Nov 25th)
- [x] IITB RM (invitation sent for Nov 8th)
- [x] Executive Director Committee (Oct 29th)
- [x] BDM (Nov 1st)
- [x] ARC (Dec 14)

[link to presentation](https://014gc.sharepoint.com/sites/TargetITSolutionDeliveryModel/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTargetITSolutionDeliveryModel%2FShared%20Documents%2Fbusiness%2Dcase%2Dproduct%2Dmgt%2Dfw%2FPresentations&viewid=3dde9f12%2D9c13%2D48a8%2D83c2%2De2beacde6db7)
