### ISSUE TITLE
MA - Review the french survey to suppliers text

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1846]
- [x] review the text
- [x] make the changes
- [x] add the french survey text to the french notify message
- [x] add the french survey text to the admin user documentation (email to send to suppliers who were not successful.docx)

**Comment by RachelMuston** [comment]
French survey text file (to review): https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Reporting/Survey-to-suppliers-email-version_FR.docx?d=wdafb86b4b19a40138621a47c34f09c75&csf=1&web=1&e=nfiQJA
English survey text file (for comparison): https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Reporting/Survey-to-suppliers-email-version_EN.docx?d=w9c01d56bd0c8430ca9352d98e9a0e66f&csf=1&web=1&e=wP9iYU
