### ISSUE TITLE
MA - Prepare presentation for IITB Showcase (Oct 29)

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1873]
- [x] draft presentation
- [x] review
- [x] translate
- [ ] create bilingual version
- [ ] finalize speaking notes
- [ ] final french review
