### ISSUE TITLE
MA - IITB newsletter item

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1874]
- [x] draft newsletter item
- [x] review and finalize newsletter item
- [x] decide on the date we want this to be in the newsletter
- [x] translate?
- [x] review french translation
- [x] draft email for Phil to send to the IITB showcase team (asking to be near the top in the newsletter)
- [x] send to the IITB newsletter team

**Comment by RachelMuston** [comment]
Sent to translation. Expected back on Sept. 10.

**Comment by RachelMuston** [comment]
French translation (to be reviewed): https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Change%20Management/Comms/IITB%20news_Micro-acquisition-pilot_FR.docx?d=wdf2e80e8432142d68f5209d1fb334f62&csf=1&web=1&e=BqJlrL

English version for reference: https://014gc.sharepoint.com/:w:/r/sites/GCDevEx/Shared%20Documents/Change%20Management/Comms/IITB%20news_Micro-acquisition-pilot.docx?d=w404740955e5842bda4958bdd95f5bb2e&csf=1&web=1&e=Ky2rFN
