### ISSUE TITLE
MA - prepare deck for exec directors meeting

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#1914]
- [x] draft deck (use an existing deck as a starting point)
- [x] review
- [x] translate
- [ ] finalize speaking notes
- [ ] send to exec directors meeting chair
