### ISSUE TITLE
Create Kick-Off Presentation

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1928]
Produce a presentation as part of the BI's kick off meeting

- [x] Backgrounder (the 12min presentation)
- [x] Present the project team's members and stakeholders
- [x] Deliverables in details
- [x] Approach of peer review
- [x] Next Steps
