### ISSUE TITLE
Peer Review - Pilot IITB Directive and Standards

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1958]
- [ ] 1st review
  - [x] WG
  - [x] Architecture - sent 2022-02-03
  - [x] BPMO - sent 2022-02-02
  - [x] Info-Tech - sent 2022-02-02
  - [ ] ~EPMO ( should wait after 1st review)~
  - [x] Job Bank - sent 2022-02-03
  ~- [ ] MyESDC Mobile App - sent 2022-02-03~
  - [x] IT Security - sent 2022-02-02
  - [x] IITB Release Management - sent 2022-02-02
  - [x] OCIO - sent 2022-02-02
  - [x] IITB RM - sent 2022-02-02
  - [x] IITB Policy - sent 2022-02-02
  - [x] BRM (HRS and SEB) - sent 2022-02-07
- [ ] 2nd review, extended to March 18th (extended email sent 2022-03-11)
  - [x] WG - sent 2022-02-24
  - [x] Architecture - sent 2022-02-24
  - [x] BPMO - sent 2022-02-24
  ~- [ ] Info-Tech~
  - [x] EPMO - sent 2022-02-24
  - [x] Job Bank - sent 2022-02-25
  ~- [ ] MyESDC Mobile App~
  - [x] IT Security - sent 2022-02-24
  - [x] IITB Release Management - sent 2022-02-24
  - [x] OCIO - sent 2022-02-24
  - [x] IITB RM - sent 2022-02-24
  ~- [ ] Policy~
  - [x] BRM (HRS and SEB) - sent 2022-02-24
- [ ] Final review
  - [ ] WG
  - [ ] Architecture
  - [ ] BPMO
  ~- [ ] Info-Tech~
  - [ ] EPMO
  ~- [ ] MyESDC Mobile App~
  - [ ] IT Security
  - [ ] IITB Release Management
  - [ ] OCIO
  - [ ] IITB RM
  ~- [ ] Policy~
  - [ ] BRM (HRS and SEB)

**Comment by remyb2canada** [comment]
2nd review reminder sent 2022-03-04
