### ISSUE TITLE
Produce deck for CIOEC

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#1977]
As per feedback from AG, produce deck for CIOEC.

Should be jointly with BPMO and with contributions from EPMO
Should include some options on how we foresee this being manifested (e.g. funding, governing)

For Jan

Peer Review the deck:
- [x] WG
- [x] BPMO / IT Strategy
- [x] EPMO (jan 21)
- [x] Exec Director (jan 25)
- [x] SABR DGO
- [x] Job Bank
- [x] MyESDC mobile app

[Draft deck here](https://014gc.sharepoint.com/:p:/r/sites/IITB-ITStrategy/Shared%20Documents/STRATEGIES%20AND%20INITIATIVES/Product%20Management/Presentations/Presentation-IITB%20Product%20Management-Overview-CIOEC.pptx?d=wb186296e2c7b4a51a99612a0819ab659&csf=1&web=1&e=FDbczl)
