### ISSUE TITLE
Consult Report

### ISSUE THREAD

**Issue by philipe-girard** [sara-sabr/ITStrategy#1979]
- [x] Write deck - Finish Considerations slide
- [x] Present to ED Committee
- [x] Present to DG Committee +
- [x] Present at IIN
- [x] Present at SLF and Showcase
- [x] Meet with - Patrice Lavoie and Michel Devenay (All directors were consulted for their review)
