### ISSUE TITLE
CS-02 Process Next Steps

### ISSUE THREAD

**Issue by philipe-girard** [sara-sabr/ITStrategy#1980]
- [x] Send invitations for the exam
- [x] Send communique to Stakeholders for exam review
- [x] Review exams and send results to HR
- [x] Book interviews
- [x] Interview candidates
- [x] Send results to HR
- [x] Create pool
- [x] Send communique to SABR for informal interviews
- [x] Send communique to IITB for informal interviews
