### ISSUE TITLE
Research Phase

### ISSUE THREAD

**Issue by philipe-girard** [sara-sabr/ITStrategy#1981]
- [x] Research Policy on Service and Digital to assess blockers
- [x] Research existing models for MOUs
- [x] Research courses/learning materials for financial delegation of authority
- [x] Create Concept briefing outline/skeleton
- [x] Meet with Luc Corbeil / Remy to better understand financial implications for staffing
- [x] Develop high level criteria and conditions under which a non-IITB group could proceed (eg. no integration, $ threshold, risk tolerance, etc.)
