### ISSUE TITLE
Closeout blog post

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#2039]
- [x] draft blog post
- [x] review
- [x] translate
- [x] create english md file
- [x] create french md file
- [x] review of md files
- [x] post

**Comment by RachelMuston** [comment]
Sent to translation on April 22
