### ISSUE TITLE
Update the micro-acquisition website

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#2040]
- [x]  add a banner to the top of the page to say that this pilot is now closed (with a link to the closeout blog post) - draft the text and translate.
- [x]  remove the mailing list form button ? Or update the GC Form? Basically we don't want folks to keep signing up
- [x] send text to translation
- [x] make the changes to the French pages
