### ISSUE TITLE
Engage PPOC - PPRC on their role in Product Management

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2055]
- [x] prep Job Bank IT
- [x] prep Job Bank business
- [x] prep SABR/Directors
- [x] send request to PPOC
