### ISSUE TITLE
Verify if there are any legal/procurement issues with openly sharing the software assessments

### ISSUE THREAD

**Issue by RachelMuston** [sara-sabr/ITStrategy#2096]
Relates to whether we are giving vendors an advantage knowing how they competitors scored in our assessment. Opening ourselves to liability? Put the question to Cassandra/Jacquie and also to ESDC legal. Upcoming activities:
- [ ] get and xls copy of an assessment document from accessibility for a COTS product
- [ ] provide legal with a copy of assessment documents from both accessibility and TA
- [ ] meet with legal

**Comment by RachelMuston** [comment]
Connection made with legal at ESDC. Meeting the week of April 11.

**Comment by RachelMuston** [comment]
Met with Legal on April 13. Legal preparing a records of decision. Legal will be providing text to use on our sharing site - something to the effect of - you can use these as inputs to your assessment process but not to replace your assessment process.
