### ISSUE TITLE
Funding software improvement explanation

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2133]
[A deck](https://014gc.sharepoint.com/:p:/r/sites/IITB-ITStrategy/Shared%20Documents/STRATEGIES%20AND%20INITIATIVES/Product%20Management/Presentations/Financing%20Different%20Software-Based%20Product%20Team%20Activities.pptx?d=w07756d82de084584a0a3519e65a2e5a1&csf=1&web=1&e=4SwDls) highlighting the different kinds of activities done on software products and how they should be financed.

Link with tech debt (IT evergreening) and the current methods of financing work in ESDC/IITB.

- [x] brainstorm with tech debt and bpmo
- [x] check with IT Strat
- [x] check with Interop Manager (jul 14)
- [x] check with Job Bank Manager
- [x] check with Pension Hub Manager (jul 11)
- [x] check with SA (jul 11)
- [x] check with Tech Debt Remediation Office
- [x] check with Resource Centre
- [x] check with IT Evergreening/Tech Debt
- [x] check with TC
- [ ] check with IITB RM 
- [x] check with EPMO
- [ ] check with CFOB IPPM (?)
