### ISSUE TITLE
Schedule consultation with EA on procedures to engage EA teams within product mgt

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2136]
e.g. intake process, fit of Solution Arch, Tech Arch, Security, Business (which is under TMB, not IITB)

- [x] EA
- [x] TA
- [x] Job Bank - Dominic
- [x] BPMO - Rodrigue
- [x] Proposal of procedures (deck)
- [x] Review with EA
- [x] Get Director Buy-in (july 20th)
