### ISSUE TITLE
Develop intake process

### ISSUE THREAD

**Issue by JSantosPS** [sara-sabr/ITStrategy#2152]
- [x] Develop intake form
- [ ] Sharepoint landing page
- [x] Service Agreement/Charter

links with #2414
