### ISSUE TITLE
Develop Communication Plan

### ISSUE THREAD

**Issue by ghost** [sara-sabr/ITStrategy#2185]
Create all communications artefacts for the SMO:

- [x] Develop intro Deck
- [ ] Identify forums to present (inspiration from [comms strategy](https://sara-sabr.github.io/ITStrategy/strategy-communications.html))
- [ ] Produce marketing material (MS teams background, One pagers, email signature addition, SharePoint Home page)
- [ ] Market new service offering
- [ ] Conduct intro-shps
