### ISSUE TITLE
Conduct Pilot

### ISSUE THREAD

**Issue by paul-tomka** [sara-sabr/ITStrategy#2186]
- [ ] Select a client opportunity and conduct pilot
- [ ] Collect feedback from client and team on pilot
- [ ] Incorporate improvement based on feedback
- [ ] Mark Pilot as Completed Successfully
