### ISSUE TITLE
Create final report

### ISSUE THREAD

**Issue by JSantosPS** [sara-sabr/ITStrategy#2371]
- [ ] Analyze interview responses
- [ ] What we heard
- [ ] Comparative analysis with first study
- [ ] Recommendations and potential actions
- [ ] Create report and accompanying summary ppt deck
