### ISSUE TITLE
PdM Framework Change Management

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2384]
- [ ] organize meeting with BRM SEB, BPMO, SSPB TMD?
- [ ] identify stakeholders?
- [ ] formalize WG (Terms of Reference)
- [ ] formalize WG (establish authority)
- [ ] Information Architecture?
  - IBVs
  - Storage Location

Produce a change management plan to:
- communicate eligibility criteria for onboarding the framework
- negotiate BRM fit
- officialize governance changes
  - procedures (e.g. PPOC/PPRC)
- communicate to stakeholders
- official handoff to "owner" (TBD)

[MS teams channel](https://teams.microsoft.com/l/channel/19%3aadd013f86a9142e6bfed2a9100dd10dd%40thread.tacv2/GT%2520en%2520Gestion%2520du%2520Produit%2520-%2520Product%2520Management%2520WG?groupId=d0a69080-6f72-4267-9b29-cde2bf40dd31&tenantId=9ed55846-8a81-4246-acd8-b1a01abfc0d1)
