### ISSUE TITLE
Setup Job Bank for PdM

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2399]
- [x] Cross-Organizational structure
- [x] Internal Governance
- [x] MOU
- [x] Product Brief

- [x] review with Job Bank (address comments)
- [x] send to BRM
