### ISSUE TITLE
Support OSS Mgmt Framework Implementation

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#99]
**Resources**

[OSS Mgmt Framework](http://dialogue/grp/TAWS-ATST/Collaboration%20Architecture%20Services/Forms/AllItems.aspx?&&p_SortBehavior=0&p_Document_x0020_Status=Final&p_FileLeafRef=ESDC%20Open%20Source%20Products%2edocx&&RootFolder=%2fgrp%2fTAWS%2dATST%2fCollaboration%20Architecture%20Services%2fProjects%2fArtificial%20Intelligence%20and%20Open%20Source%2fOSS&PageFirstRow=1&TreeField=Folders&TreeValue=Projects%2FArtificial%20Intelligence%20and%20Open%20Source%2FOSS&ProcessQStringToCAML=1&&View={8B985846-C314-4371-9874-078658155488})  
[Portal for end users (in progress)](http://dialogue/grp/CO6721427/SitePages/Home.aspx)
[GC/Code Repository](https://gccode.ssc-spc.gc.ca/iitb-dgiit/ta/esdc-open-source-software-management-framework)

**Tasks**

- [x] Meet with lead team
- [x] Review existing OSS Mgmt Framework
- [ ] Add recommendations from Daniel Buijs (HC/SC) (https://trello.com/c/gKbiMNqt/23-oss-mgmt-framework-improve-governance)
- [ ] Suggest improvements to OSS Mgmt Framework (e.g. process for release)
e.g. [OpenChain](https://www.openchainproject.org)?
- [ ] Contribute to Communication Strategy to share official OSS Mgmt Framework 
- [ ] Meet with IP Centre of Excellence (IPCOE) as required
 - http://iservice.prv/eng/finance/ip/ip_centre_excellence.shtml
 - Mailbox: NC-ASSETS-IP-POLICY-POLITIQUES-BIENS-PI-GD

e.g. [ESDC EventApp's use of MIT licence for consumption](https://github.com/esdc-edsc/EventApp), but what about contribution

From @gcharest:
Need to breakout in buckets: Using, Contributing and Publishing.
IP COE has already well established rules around publishing: DG approval required for all OSS licences and even to Public Domain.

Goes the same way for contributing: DG approval required but there's work in place to have an "automated" form for approving an employee to contribute to it.

Finally, using OSS should be broken down in whether we're using as COTS or as part of development project to help with the compliance.

From @smellems 
Using: the EA way forward seems to includes consideration (prioritization?) of OSS. We should follow and contribute!

Glad to hear there is already some processes in place for publishing and contributing. Let's work on making it easier for developers!

**Comment by smellems** [comment]
These groups are also ESDC I think
- https://github.com/esdc-devx
- https://github.com/MTS-STM

**Comment by gcharest** [comment]
Releasing OSS is on DG approval, ESDC employees contribution is part of the framework to be presented. Essentially the same but once a project is green lighted, other employees should have minimal effort to contribute too.

**Comment by gcharest** [comment]
Current process includes both applying ANY licence to Crown copyright material AND releasing in public domain: requires DG approval (delegated authority)

**Comment by gcharest** [comment]
I think this should be closed. The framework is in place, they have done amazing work and we can support by attending. No work required from our team I believe.

Reopen if needed? @gabrielcossette @smellems
